# Site identity
title: "Ecem Şimşek"
name:  "Ecem Şimşek"
description: "Graph Signal Processing • GNNs • Visibility Graphs"
url: "https://ecemsimsekk.github.io"   # canonical root
baseurl: ""                            # user site → keep empty

# Build & markdown
permalink: pretty
markdown: kramdown
kramdown:
  parse_block_html: true
  syntax_highlighter: rouge
future: true

# Local dev only (safe to keep)
port: 4000
destination: ./_site

# Show/hide the top navbar
show_nav: false

# Homepage hero controls
show_hero: true
hero_image: /assets/ecem.jpg
hero_alt: "Ecem Şimşek"

# Social / contacts (used by header or SEO tag)
github_username: ecemsimsekk
#twitter_username:
email: ecem.simsek@bilkent.edu.tr
linkedin: https://www.linkedin.com/in/ecem-%C5%9Fim%C5%9Fek-3601b618b/
scholar: https://scholar.google.com/citations?user=ZrC2RNwAAAAJ&hl=tr

# Plugins (supported by GitHub Pages)
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag    # add SEO metadata

exclude:
  - .travis.yml
  - validate.rb
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
  - node_modules
  - animations
  - blog
  - meet
  - pgp
  - bio
  - data
  - _posts
